### ISSUE TITLE
Windows Hyper-V, can't share volumns

### ISSUE THREAD

**Issue by kinger-de** [maxpou/docker-symfony#10]
Hi,

i like the modular config in this docker package and try to run it.
Everything looks fine in Kitematic. Elk restarted constantly, cause it exit always with code 1, but this is not my problem right now.

The symfony project folder are not synced with the nginx or php container. In Kitematic the folders are listed. But if i explore the files directly in the container with ls, i get an null result.

Maxence, or anybody else, do you have any hints to solve this problem?

greetings

**Comment by maxpou** [comment]
Hi,
My Docker stack run on Ubuntu sorry.
Can you show me your `docker-compose` file ?

**Comment by kinger-de** [comment]
Thank you for your answer and sorry for my late reply.
Yes, i think, it is a problem with the UAC (User Account Control) on my windows system. Normally i use an regular account without admin-rights. Docker for windows has trouble with this and can't get access to my profile folder.

I switched to the old implementation of Docker which is using VirtualBox. This seems to work.

FYI, this is my current docker file:
```
version: '2'

services:
    base:
        image: busybox:musl
        volumes:
            - ./symfony:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
            - ./logs/nginx/:/var/log/nginx
            - /var/www/symfony/var/cache
            - /var/www/symfony/var/logs
            - /tmp
        tty: true
    php:
        build: php
        expose:
            - "9000"
        links:
            - mysql
            - redis
        volumes_from:
            - base
    nginx:
        build: nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - base
    mysql:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: 
            MYSQL_DATABASE: 
            MYSQL_USER: 
            MYSQL_PASSWORD: 
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - base
```
