### ISSUE TITLE
adding nodejs image does not work

### ISSUE THREAD

**Issue by alpham8** [maxpou/docker-symfony#119]
Hi,
I tried to add the official nodejs image, so that we can run ``node`` and ``npm``.

However, by following the readme on how to add other images, this seems not to work in ``docker-compose.yml`` file:
```
    node:
        image: node:12.16.2-alpine3.9
        volumes_from:
            - php
            - nginx
```
Then I ran:
```
docker-compose down
docker-compose up -d
```
To get my added node container.

I can't access it via
```
docker-compose exec node bash
``` 
To install my dependencies in my symfony project.

Any help would be great :smile:

Cheers,
alpham8
