### ISSUE TITLE
Redis

### ISSUE THREAD

**Issue by benjaminjonard** [maxpou/docker-symfony#17]
Hello, 
First of all, thanks for your repo, it makes learning Docker with Symfony a bliss :)

I just have a question concerning the Redis part.
When using the line `redis_host: redis` I have the following error :

`Invalid configuration for path "snc_redis.clients.doctrine.dsns.0": The redis DSN "redis" is invalid.`

I had to use `redis_host: redis://redis` instead.

I'm still learning how to use Docker, am I missing something ? 
I'm using Symfony3 and SncRedisBundle.

Thanks

**Comment by maxpou** [comment]
Hello @benjaminjonard ,

If you are in the PHP container (`docker-compose exec php bash`), try to ping the redis container.
Here, is my result:

```sh
root@597b06d48146:/var/www/symfony# ping redis
PING redis (172.19.0.3): 56 data bytes
64 bytes from 172.19.0.3: icmp_seq=0 ttl=64 time=0.106 ms
64 bytes from 172.19.0.3: icmp_seq=1 ttl=64 time=0.070 ms
64 bytes from 172.19.0.3: icmp_seq=2 ttl=64 time=0.067 ms
64 bytes from 172.19.0.3: icmp_seq=3 ttl=64 time=0.077 ms
^C--- redis ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.067/0.080/0.106/0.000 ms
```

So, **redis host is reachable**.
If you are using the [SncRedisBundle](https://github.com/snc/SncRedisBundle/blob/master/Resources/doc/index.md#usage), you have to fill the configuration file like this:

```yml
#config.yml
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://localhost
```

In my README.md, I use something like that (in the parameters.yml file):

```yml
# path/to/your/symfony-project/app/config/parameters.yml
parameters:
    redis_host: redis
```

So, you need to adapt the config file like this:

```yml
snc_redis:
    clients:
        default:
            # ...
            dsn: redis://%redis_host%
```

In my humble opinion, it's not a good idea to put the full IP address/dsn in a config file. This is why I was using the parameters.yml.


Kind regards,
Maxence


Ps: close if everything is ok for you!
