### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by ikerib** [maxpou/docker-symfony#39]
Hi, I'm trying to setup my environment, everything goes ok until composer install, I can to connect to bash but ther is no code in it, it's like the volume is not correctly mounted or something.

I have my symfony app and in it's root folder I copied this repo files and mofied docker-composer.yml php section like this:

```
php:
        build: php7-fpm
        ports:
            - 9000:9000
        volumes:
            - ./:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
```

When I connected to bash I only see app/logs folder... so I can't executate composer install.... any help?
