### ISSUE TITLE
cannot docker-compose up db

### ISSUE THREAD

**Issue by zjsxwc** [maxpou/docker-symfony#50]
when i run `sudo docker-compose up db `, it failed:
```
mysqld: Can't create/write to file '/var/lib/mysql/is_writable' (Errcode: 13 - Permission denied)
```

**Comment by maxpou** [comment]
as it stand, I cannot help you.
Please provide more details such as `docker info`, logs, steps to reproduce...

The DB part of this stack come from the [original image](https://hub.docker.com/_/mysql/)...

**Comment by zjsxwc** [comment]
fix this by adding: ` user: "1000:50"`
```
    db:
        image: mysql
        user: "1000:50"
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
```
