### ISSUE TITLE
Very slow Symfony app

### ISSUE THREAD

**Issue by ktrzos** [maxpou/docker-symfony#53]
Hi,
I've god Symfony 3 application in Docker CE on my Windows 10 machine. Loading time of this app is about 4-5 seconds. Symfony initialization is about 600ms. I've got even opcache installed and that time is, still, HUGE!
What could be wrong? :(

**Comment by ktrzos** [comment]
Lowered application loading time by half when added 

```yml
services:
    php:
        volumes:
            - /var/www/symfony/vendor
```
