### ISSUE TITLE
mysql error

### ISSUE THREAD

**Issue by mediafigaro** [maxpou/docker-symfony#7]
Hello 
with this latest version I have an error with mysql due to permissions issues on Mac, please any idea I've been checking this king of issue on forums but... ?

db_1     | 2016-08-24T15:52:03.578202Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db_1     | 2016-08-24T15:52:03.595285Z 0 [Note] InnoDB: Completed initialization of buffer pool
db_1     | 2016-08-24T15:52:03.600991Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1     | 2016-08-24T15:52:03.610361Z 0 [ERROR] InnoDB: The innodb_system data file 'ibdata1' must be writable
db_1     | 2016-08-24T15:52:03.610461Z 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error

**Comment by maxpou** [comment]
Hi @mediafigaro,
Could you try this solution: 

```yml
services:
    db:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD: root
            - MYSQL_HOST=   # override from env file to be empty
```

See: https://github.com/docker-library/mysql/issues/82#issuecomment-230292558
