### ISSUE TITLE
How can i make swiftmailer work?

### ISSUE THREAD

**Issue by jakobeissler** [maxpou/docker-symfony#84]
I'm trying to send email with swiftmailer but i can't make it work. I've tried with mail, sendmail and smtp parameters but it won't send the mails.

**Comment by mjherraiz** [comment]
I had the same problem, I solve it by adding a mailcatcher container and then you can view sent emails in 
symfony.dev:1080

In docker-compose file add 
```
    mailcatcher:
        image: yappabe/mailcatcher
        ports:
            - 1025:1025
            - 1080:1080
```
And link it to php container
```
        links:
          - mailcatcher
```
Then you need to modify your params in your symfony app
```
swiftmailer:
    transport:  smtp
    host:       mailcatcher
    port:   1025
```

I hope you find it useful :)
