### ISSUE TITLE
Nginx official image

### ISSUE THREAD

**Issue by Glideh** [maxpou/docker-symfony#87]
Shouldn't we use the official nginx image instead of building one from `debian:jessie` ?
Here is what I use in my projects:

```yml
services:
# ...
  nginx:
    image: nginx:1.13
    depends_on:
      - php
    volumes:
      - ${SYMFONY_APP_PATH}/web/:/var/www/symfony/web
      - ./logs/nginx:/var/logs/nginx
      - ./symfony.conf:/etc/nginx/conf.d/default.conf
# ...
```

I don't even need to have `Dockerfile` for the service
