### ISSUE TITLE
DB connect via HeidiSQL

### ISSUE THREAD

**Issue by Migoth** [maxpou/docker-symfony#88]
Is it possible to connect to db via HeidiSQL from Windows?

**Comment by maxpou** [comment]
Hi,
You should try this: https://github.com/docker-library/mysql/issues/274

**Comment by PyRowMan** [comment]
Or you can add a shared port to the db config in the docker-compose.yml

```
db:
        image: mysql:latest
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
```
