### ISSUE TITLE
Problem fastcgi

### ISSUE THREAD

**Issue by HamHamFonFon** [maxpou/docker-symfony#99]
Hello,

I'm trying your great docker stack for a Symfony 3.4 website but i have s problem. After build and up the stack,
when i go to http://dso.test/app_dev.php, i have this message : 

> File not found. 

I have searched in log (/var/log/nginx/dso.error.log) and got this error message :
`
2018/05/19 15:21:23 [error] 7#0: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.19.0.1, server: dso.test, request: "GET /app_dev.php HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "dso.test"
`

Here's my docker-compose : 
```yml
version: "2"

services:
  redis:
    image: redis:alpine
    container_name: redis_dso
    ports:
      - 6379:6379
  php:
    build:
      context: ./docker/container/php
      args:
        TIMEZONE: ${TIMEZONE}
    container_name: php_dso
    links:
      - redis
    volumes:
     - ${SYMFONY_APP_PATH}:/var/www/dso:rw
  # NGINX
  nginx:
    build:
      context: ./docker/container/nginx
    container_name: nginx_dso
    ports:
     - 80:80
    volumes_from:
      - php
```
My symfony.conf is renamed in dso.conf and contains : 
```conf
server {
	server_name dso.test;
	root /var/www/dso/web;
	
	## Default location
	location / {
		try_files $uri @rewriteapp;
	}

    location @rewriteapp {
        rewrite ^(.*)$ /app.php/$1 last;
    }

    location ~ ^/(app_dev|config)\.php(/|$) {
        fastcgi_pass php:9000;
        # fastcgi_pass php-upstream;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS off;
		# Symfony Doc
        # fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        # fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    error_log /var/log/nginx/dso.error.log;
	access_log /var/log/nginx/dso.access.log;
}
```
I have tested with `fastcgi_pass php:9000;` or  `php-upstream;`but same problem...
I have my good host in `/etc/hosts` . I don't understand the problem and hope there is a solution :).

Edit : i'm using Debian 9 (maybe it's not important)
Thx
